### ISSUE TITLE
attempt to call method 'noBias' (a nil value)

### ISSUE THREAD

**Issue by lulu1315** [rtqichen/style-swap#1]
hello and thank you very much for the code.
I tried your example but have this error : 

th style-swap.lua --content images/content/brad_pitt.jpg --style images/style/la_muse.jpg --patchSize 7 --patchStride 3
{
  pooling : "avg"
  content : "images/content/brad_pitt.jpg"
  patchStride : 3
  optimIter : 100
  learningRate : 0.05
  maxContentSize : 640
  printEvery : 50
  decoder : ""
  init : "content"
  maxStyleSize : 512
  style : "images/style/la_muse.jpg"
  saveOriginal : false
  numSwap : 1
  saveLoss : false
  optim : false
  patchSize : 7
  save : "output"
  gpu : 0
  tv : 1e-07
  layer : "relu3_1"
  contentBatch : ""
}
Loading Lua modules...
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
nn.Sequential {
  [input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> (11) -> (12) -> (13) -> (14) -> (15) -> output]
  (1): cudnn.SpatialConvolution(3 -> 3, 1x1)
  (2): nn.TVLossModule
  (3): cudnn.SpatialConvolution(3 -> 64, 3x3, 1,1, 1,1)
  (4): cudnn.ReLU
  (5): cudnn.SpatialConvolution(64 -> 64, 3x3, 1,1, 1,1)
  (6): cudnn.ReLU
  (7): cudnn.SpatialAveragePooling(2x2, 2,2)
  (8): cudnn.SpatialConvolution(64 -> 128, 3x3, 1,1, 1,1)
  (9): cudnn.ReLU
  (10): cudnn.SpatialConvolution(128 -> 128, 3x3, 1,1, 1,1)
  (11): cudnn.ReLU
  (12): cudnn.SpatialAveragePooling(2x2, 2,2)
  (13): cudnn.SpatialConvolution(128 -> 256, 3x3, 1,1, 1,1)
  (14): cudnn.ReLU
  (15): nn.ContentLossModule
}
/home/me/torch/install/bin/luajit: ./lib/NonparametricPatchAutoencoderFactory.lua:59: attempt to call method 'noBias' (a nil value)
stack traceback:
        ./lib/NonparametricPatchAutoencoderFactory.lua:59: in function '_build'
        ./lib/NonparametricPatchAutoencoderFactory.lua:17: in function 'buildAutoencoder'
        style-swap.lua:152: in main chunk
        [C]: in function 'dofile'
        ...uluf/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670
I'm on Kubuntu 14.04 / Torch7 / lua5.1
thanks in advance

**Comment by rtqichen** [comment]
Hi, thanks for trying it out!
I think you're behind a few updates on Torch. Try
```
luarocks install nn
luarocks install cudnn
```

**Comment by lulu1315** [comment]
thanks for your response
luarocks install nn throws error while compiling
should I reinstall torch from scratch maybe?
which version are you using?

**Comment by rtqichen** [comment]
Yes you might want to try that. Or maybe start with `luarocks install torch`.
The error you have is due to SpatialFullConvolution not having noBias() implemented. This function was implemented some time around June this year..

**Comment by lulu1315** [comment]
ok.I did:
luarocks install torch
luarocks install nn
luarocks install cdnn
luarocks install cutorch
it installs fine.

now I have this error : 

th style-swap.lua --content images/content/bike.jpg --style images/style/starry_night.jpg
{
  pooling : "avg"
  content : "images/content/bike.jpg"
  contentBatch : ""
  optimIter : 100
  learningRate : 0.05
  maxContentSize : 640
  printEvery : 50
  layer : "relu3_1"
  init : "content"
  maxStyleSize : 512
  style : "images/style/starry_night.jpg"
  saveOriginal : false
  numSwap : 1
  saveLoss : false
  patchStride : 1
  patchSize : 3
  optim : false
  save : "output"
  gpu : 0
  tv : 1e-07
  decoder : ""
}
Loading Lua modules...
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
nn.Sequential {
  [input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> (11) -> (12) -> (13) -> (14) -> (15) -> output]
  (1): cudnn.SpatialConvolution(3 -> 3, 1x1)
  (2): nn.TVLossModule
  (3): cudnn.SpatialConvolution(3 -> 64, 3x3, 1,1, 1,1)
  (4): cudnn.ReLU
  (5): cudnn.SpatialConvolution(64 -> 64, 3x3, 1,1, 1,1)
  (6): cudnn.ReLU
  (7): cudnn.SpatialAveragePooling(2x2, 2,2)
  (8): cudnn.SpatialConvolution(64 -> 128, 3x3, 1,1, 1,1)
  (9): cudnn.ReLU
  (10): cudnn.SpatialConvolution(128 -> 128, 3x3, 1,1, 1,1)
  (11): cudnn.ReLU
  (12): cudnn.SpatialAveragePooling(2x2, 2,2)
  (13): cudnn.SpatialConvolution(128 -> 256, 3x3, 1,1, 1,1)
  (14): cudnn.ReLU
  (15): nn.ContentLossModule
}
nn.Sequential {
  [input -> (1) -> (2) -> (3) -> output]
  (1): nn.SpatialConvolution(256 -> 9828, 3x3) without bias
  (2): nn.MaxCoord
  (3): nn.Sequential {
    [input -> (1) -> (2) -> output]
    (1): nn.ConcatTable {
      input
        |`-> (1): nn.SpatialFullConvolution(9828 -> 256, 3x3) without bias
         `-> (2): nn.Sequential {
               [input -> (1) -> (2) -> (3) -> (4) -> (5) -> output]
               (1): nn.Sum
               (2): nn.Unsqueeze(dim 1)
               (3): nn.SpatialFullConvolution(1 -> 1, 3x3) without bias
               (4): nn.Squeeze
               (5): nn.Replicate
             }
         ... -> output
    }
    (2): nn.CDivTable
  }
}
Creating save folder at output
/home/luluf/torch/install/bin/luajit: /home/luluf/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 1 module of nn.Sequential:
/home/luluf/torch/install/share/lua/5.1/nn/THNN.lua:110: bad argument #4 to 'v' (weight tensor must be 2D (nOutputPlane,nInputPlane*kH*kW) at /tmp/luarocks_cunn-scm-1-2307/cunn/lib/THCUNN/SpatialConvolutionMM.cu:13)
stack traceback:
        [C]: in function 'v'
        /home/luluf/torch/install/share/lua/5.1/nn/THNN.lua:110: in function 'SpatialConvolutionMM_updateOutput'
        ...uf/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:79: in function <...uf/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:76>
        [C]: in function 'xpcall'
        /home/luluf/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        /home/luluf/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
        style-swap.lua:176: in function 'swapTransfer'
        style-swap.lua:221: in main chunk
        [C]: in function 'dofile'
        ...uluf/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
        [C]: in function 'error'
        /home/luluf/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
        /home/luluf/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
        style-swap.lua:176: in function 'swapTransfer'
        style-swap.lua:221: in main chunk
        [C]: in function 'dofile'
        ...uluf/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

sorry to be a pain :)
I'm running cuda 7.5

**Comment by rtqichen** [comment]
No worries. You also need to update cunn: `luarocks install cunn`.

**Comment by lulu1315** [comment]
bingo.
time for fun.
thanks
