### ISSUE TITLE
 input has to contain: 3 feature maps, but received input of size: 1 x 4 x 512 x 371

### ISSUE THREAD

**Issue by Sugarbank** [rtqichen/style-swap#10]
Sometimes I get this error, any ideas?

Loading Lua modules...	
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:605] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:82] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
nn.Sequential {
  [input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> (11) -> (12) -> (13) -> (14) -> (15) -> output]
  (1): cudnn.SpatialConvolution(3 -> 3, 1x1)
  (2): nn.TVLossModule
  (3): cudnn.SpatialConvolution(3 -> 64, 3x3, 1,1, 1,1)
  (4): cudnn.ReLU
  (5): cudnn.SpatialConvolution(64 -> 64, 3x3, 1,1, 1,1)
  (6): cudnn.ReLU
  (7): cudnn.SpatialAveragePooling(2x2, 2,2)
  (8): cudnn.SpatialConvolution(64 -> 128, 3x3, 1,1, 1,1)
  (9): cudnn.ReLU
  (10): cudnn.SpatialConvolution(128 -> 128, 3x3, 1,1, 1,1)
  (11): cudnn.ReLU
  (12): cudnn.SpatialAveragePooling(2x2, 2,2)
  (13): cudnn.SpatialConvolution(128 -> 256, 3x3, 1,1, 1,1)
  (14): cudnn.ReLU
  (15): nn.ContentLossModule
}
/Users/zSUGARBANK/torch/install/bin/luajit: .../zSUGARBANK/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 1 module of nn.Sequential:
...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:102: input has to contain: 3 feature maps, but received input of size: 1 x 4 x 512 x 371
stack traceback:
	[C]: in function 'assert'
	...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:102: in function 'checkInputChanged'
	...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:120: in function 'createIODescriptors'
	...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:187: in function <...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:185>
	[C]: in function 'xpcall'
	.../zSUGARBANK/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	...zSUGARBANK/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	...RENDER_APP/REF_SOFTWARE/style-swap-master/style-swap.lua:165: in main chunk
	[C]: in function 'dofile'
	...BANK/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x01038cdd00

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	.../zSUGARBANK/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	...zSUGARBANK/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	...RENDER_APP/REF_SOFTWARE/style-swap-master/style-swap.lua:165: in main chunk
	[C]: in function 'dofile'
	...BANK/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x01038cdd00
S

**Comment by rtqichen** [comment]
Sorry for the delay. I'm not quite sure. Can you send me the image that causes this error?

**Comment by Sugarbank** [comment]
![brushes_01](https://cloud.githubusercontent.com/assets/10692268/23007179/efd87530-f45a-11e6-8d40-183b1d15d6bc.jpg)

**Comment by rtqichen** [comment]
Thanks! Fixed.

**Comment by Sugarbank** [comment]
out of interest what was causing the error?
Sometimes also I get a smaller output than the input size.By a strange amoutn like 15 pixels or something.It's almost as if it's cropping the image?

**Comment by rtqichen** [comment]
I was reading the image as grayscale and wasn't getting the 3 RGB channels, which are used by the CNN.

As for cropping, it's because the CNN implicitly crops images. I think the height and width are required to be a multiple of 8 or 4 (can't remember which), otherwise it gets cropped.
