### ISSUE TITLE
Always out of memory. Strange.

### ISSUE THREAD

**Issue by xiesiyuan** [rtqichen/style-swap#14]
I have 4 G1080, each has 8G memory. Only 1 used, and only 1.5G cost. 

However, always out of memory when I am trying to see what will happen for 'relu1_1'.

**Comment by xiesiyuan** [comment]
@rtqichen

**Comment by rtqichen** [comment]
This is because when using relu1_1, the number of patches is H*W of the image. This creates a conv layer of H*W number of filters due to the style swap implementation. Maybe try CPU mode? The code I used for testing relu1_1/relu2_1 use ugly loops and are not available on github.
