### ISSUE TITLE
why not directly  use cnn  to approximate the entire net?

### ISSUE THREAD

**Issue by xiesiyuan** [rtqichen/style-swap#15]
Will that be interesting? Now the  approximate process is only for the final optimation, however, the speed is too slow to stylize video anyway.  If use CNN  (like what jcjohn did in fast neural art, loss function defined to be the distance  between swapped, optimal image and the sylized image forward through CNN) to approximate not only optimation together with swap step. The speed may be faster?

**Comment by rtqichen** [comment]
When I tried this, it either couldn't generalize or just gave perceptually bad images.
There are two works that I'm aware of that follow this one, you might find them interesting:
- https://openreview.net/forum?id=H1Y7-1HYg&noteId=H1Y7-1HYg
- https://arxiv.org/abs/1703.06868

**Comment by xiesiyuan** [comment]
Thx, Chen. 

By the way, as you said, I could not see the quality advantage to fast-neural-style (jcjohn) indeed,, except for arbitrarily shifting the style image  .
