### ISSUE TITLE
I wonder does this script has advantage of faster speed compared to that of CNNMRF?

### ISSUE THREAD

**Issue by LambdaWill** [rtqichen/style-swap#18]
I haven't look into the code of CNNMRF, it seems that it has a different way of implement. [mrf](https://github.com/chuanli11/CNNMRF/blob/master/mylib/mrf.lua). Thank you in advance!

**Comment by rtqichen** [comment]
Yes, I don't remember the specifics of it but I think they did it iteratively by blocks which is incredibly slow.
