### ISSUE TITLE
cuda runtime error (2) : out of memory at THCStorage.cu:65

### ISSUE THREAD

**Issue by Sugarbank** [rtqichen/style-swap#2]
Hi i'm getting this error when trying different images, it works with some but not others.

MACOSX 10.11.3
iMac (27-inch, Late 2013)

Christians-iMac:style-swap-master zSUGARBANK$ th style-swap.lua --content images/content/boat.png --style images/style/woman-with-hat-matisse.jpg
{
  pooling : "avg"
  content : "images/content/boat.png"
  contentBatch : ""
  optimIter : 100
  learningRate : 0.05
  maxContentSize : 640
  printEvery : 50
  layer : "relu3_1"
  init : "content"
  maxStyleSize : 512
  style : "images/style/woman-with-hat-matisse.jpg"
  saveOriginal : false
  numSwap : 1
  saveLoss : false
  patchStride : 1
  patchSize : 3
  optim : false
  save : "output"
  gpu : 0
  tv : 1e-07
  decoder : ""
}
Loading Lua modules...	
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:605] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:82] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
nn.Sequential {
  [input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> (11) -> (12) -> (13) -> (14) -> (15) -> output]
  (1): cudnn.SpatialConvolution(3 -> 3, 1x1)
  (2): nn.TVLossModule
  (3): cudnn.SpatialConvolution(3 -> 64, 3x3, 1,1, 1,1)
  (4): cudnn.ReLU
  (5): cudnn.SpatialConvolution(64 -> 64, 3x3, 1,1, 1,1)
  (6): cudnn.ReLU
  (7): cudnn.SpatialAveragePooling(2x2, 2,2)
  (8): cudnn.SpatialConvolution(64 -> 128, 3x3, 1,1, 1,1)
  (9): cudnn.ReLU
  (10): cudnn.SpatialConvolution(128 -> 128, 3x3, 1,1, 1,1)
  (11): cudnn.ReLU
  (12): cudnn.SpatialAveragePooling(2x2, 2,2)
  (13): cudnn.SpatialConvolution(128 -> 256, 3x3, 1,1, 1,1)
  (14): cudnn.ReLU
  (15): nn.ContentLossModule
}
nn.Sequential {
  [input -> (1) -> (2) -> (3) -> output]
  (1): nn.SpatialConvolution(256 -> 11592, 3x3) without bias
  (2): nn.MaxCoord
  (3): nn.Sequential {
    [input -> (1) -> (2) -> output]
    (1): nn.ConcatTable {
      input
        |`-> (1): nn.SpatialFullConvolution(11592 -> 256, 3x3) without bias
         `-> (2): nn.Sequential {
               [input -> (1) -> (2) -> (3) -> (4) -> (5) -> output]
               (1): nn.Sum
               (2): nn.Unsqueeze(dim 1)
               (3): nn.SpatialFullConvolution(1 -> 1, 3x3) without bias
               (4): nn.Squeeze
               (5): nn.Replicate
             }
         ... -> output
    }
    (2): nn.CDivTable
  }
}
Creating save folder at output	
THCudaCheck FAIL file=/Users/zSUGARBANK/torch/extra/cutorch/lib/THC/generic/THCStorage.cu line=65 error=2 : out of memory
/Users/zSUGARBANK/torch/install/bin/luajit: .../zSUGARBANK/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 2 module of nn.Sequential:
...SUGARBANK/torch/install/share/lua/5.1/cutorch/Tensor.lua:14: cuda runtime error (2) : out of memory at /Users/zSUGARBANK/torch/extra/cutorch/lib/THC/generic/THCStorage.cu:65
stack traceback:
	[C]: in function 'resize'
	...SUGARBANK/torch/install/share/lua/5.1/cutorch/Tensor.lua:14: in function 'type'
	./lib/MaxCoord.lua:42: in function <./lib/MaxCoord.lua:11>
	[C]: in function 'xpcall'
	.../zSUGARBANK/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	...zSUGARBANK/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	style-swap.lua:176: in function 'swapTransfer'
	style-swap.lua:221: in main chunk
	[C]: in function 'dofile'
	...BANK/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x01036dad00

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	.../zSUGARBANK/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	...zSUGARBANK/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	style-swap.lua:176: in function 'swapTransfer'
	style-swap.lua:221: in main chunk
	[C]: in function 'dofile'
	...BANK/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x01036dad00

**Comment by rtqichen** [comment]
You're running out of memory on your GPU. A good way to reduce memory is to increase `--patchStride` (default is 1, so try 2 or higher). You can also tweak (lower) `--maxStyleSize`.

**Comment by Sugarbank** [comment]
Is it possible to disable gpu and only use cpu?





On Sat, Dec 24, 2016 at 4:29 AM +1100, "Ricky Chen" <notifications@github.com<mailto:notifications@github.com>> wrote:


You're running out of memory on your GPU. A good way to reduce memory is to increase --patchStride (default is 1, so try 2 or higher). You can also tweak (lower) --maxStyleSize.

**Comment by rtqichen** [comment]
Sorry, CPU-only isn't implemented.

**Comment by Sugarbank** [comment]
Would it be hard to implement cpu so resolution doesn't max out gpu?





On Sat, Dec 24, 2016 at 4:36 AM +1100, "Ricky Chen" <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry, CPU-only isn't implemented.

**Comment by Sugarbank** [comment]
By the way.really amazing work here😀





On Sat, Dec 24, 2016 at 4:37 AM +1100, "Christian J Heinrich" <sugarbank@hotmail.com<mailto:sugarbank@hotmail.com>> wrote:

Would it be hard to implement cpu so resolution doesn't max out gpu?





On Sat, Dec 24, 2016 at 4:36 AM +1100, "Ricky Chen" <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry, CPU-only isn't implemented.

**Comment by rtqichen** [comment]
I've added CPU-only mode: 3225a51fa19d77d176b96fb5436521cfd06695ba. You can specify CPU-only with the `--cpu` flag. Beware it's quite slow (~5min on a good CPU).
It was easier than I expected, though it isn't fully tested on a CPU-only machine yet.. Oh well. Closing this issue unless something comes up again.
