### ISSUE TITLE
Style Batch

### ISSUE THREAD

**Issue by Sugarbank** [rtqichen/style-swap#21]
Hi just wondering how hard it would be to make a stylebatch flag that works similar to content batch?

**Comment by rtqichen** [comment]
Not that hard but I probably won't do it. There likely won't be much of a speed gain, and you can write a bash script to call styleswap.lua in a for loop to achieve the same thing.

**Comment by rtqichen** [comment]
i mean something like this:

```
#!/bin/bash
foldername=$1
for i in $( ls $1 );
do
    th style-swap.lua --style $1/$i
done
```
place this in a file e.g. `stylebatch.sh` and call it using `bash stylebatch.sh <foldername>`.
