### ISSUE TITLE
Can you provide the torch model of the inverse network ??

### ISSUE THREAD

**Issue by xdyjw** [rtqichen/style-swap#22]
Can you provide the torch model you trained of the inverse network ??

**Comment by rtqichen** [comment]
Sure, just send me a email.

**Comment by qieaaa** [comment]
@rtqichen hi, can you also provide me a trained inverse network ? thank you very much!
my email is  huangzhenyu1992@gmail.com

**Comment by AndreJFBico** [comment]
Hi, id like the model as well, tori789@gmail.com

Thanks in advance!

**Comment by sinhprous** [comment]
Can you provide me the model as well? Thanks! [snsinhson938@gmail.com](snsinhson938@gmail.com)

**Comment by psychosomaticdragon** [comment]
I'd like a copy of the model as well thanks! eris.rudkin@gmail.com

**Comment by JarveeLee** [comment]
I'd like a copy of inverse model as well,thanks~ 798038012@qq.com
