### ISSUE TITLE
StylePatchLoss is not quite consistent Nonparametric ?

### ISSUE THREAD

**Issue by LambdaWill** [rtqichen/style-swap#27]
In your train-vgg-decoder, you call Nonparametric. However, you apply StylePatchLoss in your style-swap. In `Nonparametric`, it contains `interpolate` which is default true. I am wondering how
much `interpolate` can affect. Also, why set `false, false, true` to the last three params of `Nonparametirc`? Especially, you set `normalize`  false , however, `interpolate` true.

**Comment by rtqichen** [comment]
`normalize` will normalize the content patches (divide by 2-norm of each individual patch). As computing the nearest neighbor for each content patch doesn't depend on this, we can forego this normalization to speed up computation.
`interpolate`will determine how elements that belong to two or more different overlapping patches will be computed. If it's false, then the value is equal to the sum of the overlapping patches. If it's true, it will be the average.'
Of the three options `shuffle`, `normalize` and `interpolate`, only `interpolate` will actually change the output of style swapping.
