### ISSUE TITLE
module 'nninit' not found:No LuaRocks module found for nninit

### ISSUE THREAD

**Issue by Sugarbank** [rtqichen/style-swap#3]
When trying to train I'm getting this missing module, can't seem to find much info online about this?

{
  displayPort : 8000
  learningRate : 0.001
  displayEvery : 20
  imageSize : 256
  pixelLoss : 0
  printEvery : 10
  save : "vgginv"
  maxIter : 80000
  displayAddr : "0.0.0.0"
  tconv : false
  gpu : 0
  learningRateDecay : 0.0001
  numSamples : 2
  tv : 1e-06
  activation : "relu"
  subpixelConv : 0
  resume : ""
  saveEvery : 500
  upsample : "nn"
  normalize : false
  styleDir : "/Volumes/style-swap-master/images/STYLES_TO_TRAIN"
  instanceNorm : false
  targetLayer : "relu3_1"
  weightDecay : 0
  contentDir : "/Volumes//style-swap-master/images/content"
  display : false
}

/Users/zSUGARBANK/torch/install/bin/luajit: ...rs/zSUGARBANK/torch/install/share/lua/5.1/trepl/init.lua:389: module 'nninit' not found:No LuaRocks module found for nninit
	no field package.preload['nninit']
	no file '/Users/zSUGARBANK/.luarocks/share/lua/5.1/nninit.lua'
	no file '/Users/zSUGARBANK/.luarocks/share/lua/5.1/nninit/init.lua'
	no file '/Users/zSUGARBANK/torch/install/share/lua/5.1/nninit.lua'
	no file '/Users/zSUGARBANK/torch/install/share/lua/5.1/nninit/init.lua'
	no file './nninit.lua'
	no file '/Users/zSUGARBANK/torch/install/share/luajit-2.1.0-beta1/nninit.lua'
	no file '/usr/local/share/lua/5.1/nninit.lua'
	no file '/usr/local/share/lua/5.1/nninit/init.lua'
	no file '/Users/zSUGARBANK/.luarocks/lib/lua/5.1/nninit.so'
	no file '/Users/zSUGARBANK/torch/install/lib/lua/5.1/nninit.so'
	no file './nninit.so'
	no file '/usr/local/lib/lua/5.1/nninit.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	...rs/zSUGARBANK/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	train-vgg-decoder.lua:57: in main chunk
	[C]: in function 'dofile'
	...BANK/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x010086bd00

**Comment by rtqichen** [comment]
Oh you're just missing the nninit module. Try `luarocks install nninit`.
