### ISSUE TITLE
libprotobuf.14.dylib not loaded

### ISSUE THREAD

**Issue by gaoyangyiqiao** [rtqichen/style-swap#38]
When I try to run style-swap.lua, it will report below:
```
 Library not loaded: /usr/local/opt/protobuf/lib/libprotobuf.14.dylib
  Referenced from: /Users/gaoyang/torch/install/lib/lua/5.1/libloadcaffe.so
  Reason: image not found
```
could anyone tell how to fix this?
Best wishes!

**Comment by rtqichen** [comment]
Oh you proabably just need loadcaffe. Do `luarocks install loadcaffe`.

**Comment by gaoyangyiqiao** [comment]
@rtqichen Thanks a lot! It works well!
