### ISSUE TITLE
Weight for TV loss [Higher = Blur]

### ISSUE THREAD

**Issue by Sugarbank** [rtqichen/style-swap#8]
Hi just wondering if you could expand on the usage of this and watch the extreme values to play with would be?
Thanks so much

--tv                    (default 1e-7)          Weight for TV loss [Higher = Blur]

**Comment by rtqichen** [comment]
Sure. The total variance (TV) regularization term basically tries to make every pixel value close to the value of its neighbours. This basically smooths the image. The best way to minimize this term is to make the entire image one color, but of course that's not desirable. The use here is to get rid of some weird patterns in the image by smoothing out the image using a small-enough-but-not-too-large --tv value. (Try setting `--tv 0` and you'll see what I mean by weird pattern.)
